### ISSUE TITLE
Tagging of nary dataset

### ISSUE THREAD

**Issue by cnachteg** [ncbi/bert_gt#3]
Hello @ptlai  !

Thank you so much for the avaibility of the code and the data !

While I was writing my own code for a custom dataset, I was trying to understand if the good results obtained by the nary dataset were obtained due to their dependency graph (obtained with Stanford) compared to the others (obtained with spacy), as it is the biggest differences with the other datasets, excluding the fact that it is also balanced.

However, I discovered that the nary dataset after preprocessing that the tagging part, where you replace the entities by their tag, does not look right.

For example, for the sentence : 

> “As compared to the large number of secondary resistance mutations noted in acquired imatinib resistance in CML , in the case of EGFR-TK , there are currently only several documented resistance point mutations to **gefitinib** and erlotinib , including **T790M** [ , ] , L747S [ ] and D761Y [ ] .” 

where gefitinib and T790M are the drug and variant of interest, it should be transformed to 

> “As compared to the large number of secondary resistance mutations noted in acquired imatinib resistance in CML , in the case of EGFR-TK , there are currently only several documented resistance point mutations to **@DRUG$** and erlotinib , including **@VARIANT$** [ , ] , L747S [ ] and D761Y [ ] .”

However, in this case, in the data I have
> “As compared to the large number of secondary resistance mutations noted in acquired imatinib resistance in CML , in the case of EGFR-TK , there are currently only several documented resistance point mutations to **@DRUG$ gefitinib** and erlotinib , including **@VARIANT$ T790M** [ , ] , L747S [ ] and D761Y [ ] .”

Is it normal ? I am afraid that this could be a source of leaked information during the learning process and could result in overfitting.

Thank you for your attention !

**Comment by ptlai** [comment]
Hi @cnachteg ,

Sorry for the late reply. Thank you for your interest in our work!

I pre-processed the n-ary dataset according to "N-ray Relation Extraction using Graph State LSTM."
Their implementation does not mask the named entities (it is at https://github.com/freesunshine0316/nary-grn/blob/master/gs_lstm/G2S_data_stream.py), where it loads the JSON file's "label" into word list.

If you want to use the masking, you could replace convert_iob2_to_tagged_sent() of convert_nary_2_bert_gt.py with convert_iob2_to_tagged_sent() of our latest implementation for BioRED (https://github.com/ncbi/bert_gt/blob/master/src/dataset_format_converter/convert_biored_2_bert_gt.py).
And set parameters as below:
```
def convert_iob2_to_tagged_sent(
        tokens, 
        labels, 
        in_neighbors_list,
        token_offset = 0,
        to_mask_src_and_tgt = True,
        has_end_tag = False)
```

Please let me know if you need help or have any questions. Thank you.

**Comment by cnachteg** [comment]
Hi @ptlai !

Thank you very much, I will also take a look at BioRED 😄 

Have a nice day !
