### ISSUE TITLE
Unable to understand processed data

### ISSUE THREAD

**Issue by nency2** [ncbi/bert_gt#4]
What information is depicted by a column after processing the CDR dataset is not clear. kindly explain

**Comment by ptlai** [comment]
Hi @nency2,

The columns are as below:
1. index: unique pair id
2. id1: ID1
3. id2: ID2
4. is_in_same_sent: Whether id1 and id2 co-occur in the same sentence.
5. min_sents_window: The minimum number of sentences between id1 and id2.
6. sentence: Abstract
7. in_neighbors: The number denotes the token indexes which have dependency edges to the current token.
8. label: Relation label

**Comment by nency2** [comment]
Thanks
