### ISSUE TITLE
Run model on new abstracts

### ISSUE THREAD

**Issue by sanyabt** [ncbi/bert_gt#5]
Hi @potinglai, thank you for making these models available! I am interested in running the bert_gt model on new PubMed abstracts for a class assignment to show the latest methods in relation extraction. I ran the model on the BioRED data using the steps in the README file but am not sure how I can use the trained model for processing new abstracts and showing the outputs. I also tried downloading the PubMedBERT model from the BioRED repository (https://github.com/ncbi/BioRED) but was not able to load with tensorflow successfully as the documentation isn't complete. Any help would be appreciated. Thank you!

**Comment by ptlai** [comment]
Hi @sanyabt,

For the bert_gt problem:

You can replace the "Test.PubTator" with your own data in PubTator format. 
You have to use the NE types of BioRED, but the relation and novelty information can be empty.
After replacement, you can execute 
`python src/dataset_format_converter/convert_biored_2_bert_gt.py`
It will convert your "Test.PubTator" into our format.
Please let me know if you have any problems. Thank you.

For the biored problem:

Could you share your error message in https://github.com/ncbi/BioRED/issues ? Thank you so much!

**Comment by sanyabt** [comment]
Thank you so much! I will try this out and let you know - closing issue for now. I will create a new issue in biored.
